services:
  django_container:
    container_name: django_app
    build:
      context: ./container
      dockerfile: Dockerfile.local
    ports:
      - 8000:8000 
    tty: true
    volumes:
      - ${SRC_PATH}:/root/workspace
    command: python ./manage.py runserver 0.0.0.0:8000